@startuml

title VSCP core time

participant "Node::Application" as app
participant "Node::VSCPCore" as node
participant "Segment Controller" as segctrl

note over app, node: Power-up

app -> node: Initialize VSCP core.
activate app
activate node
node -> node: Initialize timeSinceEpoch to 0.
node --> app
deactivate node
deactivate app

alt If RTC available
    app -> node: Set timeSinceEpoch with RTC.
    activate app
    activate node
    node --> app
    deactivate node
    deactivate app
end alt

note over app, node: Standard processing

app -> node: Process VSCP core.
activate app
activate node

alt Every second
    node -> node: Increase timeSinceEpoch.
end alt

node --> app
deactivate app
deactivate node

note over node,segctrl: Segment controller synchronizes the time.

segctrl ->> node: Heartbeat with timestamp.

app -> node: Process VSCP core.
activate node

node -> node: Update timeSinceEpoch with received timestamp.

node --> app

deactivate node

alt If RTC available

    note over app, node: Synchronize RTC once per day.
    
    app -> node: Get timeSinceEpoch.
    
    activate app
    activate node
    
    node --> app: Return timeSinceEpoch.
    
    deactivate node
    
    app -> app: Update RTC with read timestamp.
    
    deactivate app

end alt

@enduml
