@startuml

title VSCP-framework statemachine

state STARTUP: entry / Blink lamp slow\nexit to INIT / init(PROBE_MASTER)
state INIT: entry / Blink lamp fast
state PREACTIVE: exit to INIT / init(PROBE)\nexit to ACTIVE / Stop timer.
state ACTIVE: entry / Set lamp on
state IDLE: entry / Set lamp off
state RESET: entry / Set lamp off
state ERROR: entry / Set lamp off

[*] --> STARTUP

STARTUP --> INIT: [No nickname id assigned.] AND\n( [Init triggered by user] OR\n[Start-up control set to immediate start] )
STARTUP --> ACTIVE: [Nickname id already assigned.]
STARTUP --> ERROR

state INIT {

    state PROBE_MASTER: entry / Probe for segment master.\nexit / Start timer.
    state PROBE_MASTER_WAIT
    state PROBE_WAIT: exit / Stop timer if node acknowledge received.
    state PROBE: entry / Probe for nickname id\nexit to PROBE_WAIT / Start timer.

    [*] -> PROBE_MASTER
    [*] --> PROBE
    
    PROBE_MASTER --> PROBE_MASTER_WAIT
    
    PROBE_MASTER_WAIT --> PROBE: [Timeout]
    PROBE_MASTER_WAIT -> PREACTIVE: [Segment master\nacknowledge received.]
    
    PROBE --> IDLE: [Segment is full]
    PROBE --> PROBE_WAIT

    PROBE_WAIT --> PROBE: [Node acknowledge received.] )
    PROBE_WAIT -> ACTIVE: [Timeout]
}

PREACTIVE -> INIT: [Timeout]
PREACTIVE --> ACTIVE: [Nickname id received from\nsegment master.]

ACTIVE --> IDLE

ACTIVE --> RESET

IDLE --> [*]

RESET --> [*]

ERROR --> [*]

@enduml