/* The MIT License (MIT)
 *
 * Copyright (c) 2014 - 2018, Andreas Merkle
 * http://www.blue-andi.de
 * vscp@blue-andi.de
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/*******************************************************************************
    DESCRIPTION
*******************************************************************************/
/**
@brief  User specific persistency access.
@file   vscp_ps_user.c
@author Andreas Merkle, http://www.blue-andi.de

@section desc Description
@see vscp_ps_user.h

This file is automatically generated. Don't change it manually.

*******************************************************************************/

/*******************************************************************************
    INCLUDES
*******************************************************************************/
#include "vscp_ps_user.h"
#include "vscp_types.h"
#include "vscp_ps_access.h"

/*******************************************************************************
    COMPILER SWITCHES
*******************************************************************************/

/*******************************************************************************
    CONSTANTS
*******************************************************************************/

/*******************************************************************************
    MACROS
*******************************************************************************/

/*******************************************************************************
    TYPES AND STRUCTURES
*******************************************************************************/

/*******************************************************************************
    PROTOTYPES
*******************************************************************************/

/*******************************************************************************
    LOCAL VARIABLES
*******************************************************************************/

/*******************************************************************************
    GLOBAL VARIABLES
*******************************************************************************/

/*******************************************************************************
    GLOBAL FUNCTIONS
*******************************************************************************/

/**
 * This function initializes this module.
 */
extern void vscp_ps_user_init(void)
{
    /* Nothing to do. */

    return;
}

/**
 * This function reads the button enable from persistent storage.
 * Enable or disable a button. There are up to 8 buttons enumerated by 1 to 8.
 * The button 1 corresponds to bit 0 and etc.
 * A 0 disables the button and a 1 enables it.
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readButtonEnable(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_BUTTON_ENABLE);
}

/**
 * This function writes the button enable to persistent storage.
 * Enable or disable a button. There are up to 8 buttons enumerated by 1 to 8.
 * The button 1 corresponds to bit 0 and etc.
 * A 0 disables the button and a 1 enables it.
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeButtonEnable(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_BUTTON_ENABLE, value);

    return;
}

/**
 * This function reads the wind enable from persistent storage.
 * Enable or disable the wind measurement.
 * A 0 disables the wind measurement and a 1 enables it.
 * Note, that if the wind measurement is enabled, the button 8 functionality will be disabled.
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readWindEnable(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_WIND_ENABLE);
}

/**
 * This function writes the wind enable to persistent storage.
 * Enable or disable the wind measurement.
 * A 0 disables the wind measurement and a 1 enables it.
 * Note, that if the wind measurement is enabled, the button 8 functionality will be disabled.
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeWindEnable(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_WIND_ENABLE, value);

    return;
}

/**
 * This function reads the relay enable from persistent storage.
 * Enable or disable a relay. There are up to 8 relays enumerated by 1 to 8.
 * The relay 1 corresponds to bit 0 and etc.
 * A 0 disables the relay and a 1 enables it.
 * Please note, that if a shutter is enabled, it doesn't matter that the relays are disabled here.
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readRelayEnable(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_RELAY_ENABLE);
}

/**
 * This function writes the relay enable to persistent storage.
 * Enable or disable a relay. There are up to 8 relays enumerated by 1 to 8.
 * The relay 1 corresponds to bit 0 and etc.
 * A 0 disables the relay and a 1 enables it.
 * Please note, that if a shutter is enabled, it doesn't matter that the relays are disabled here.
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeRelayEnable(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_RELAY_ENABLE, value);

    return;
}

/**
 * This function reads the shutter enable from persistent storage.
 * Enable or disable a shutter. There are up to 4 shutter enumerated by 1 to 4.
 * The shutter 1 corresponds to bit 0 and etc.
 * A 0 disables the shutter and a 1 enables it.
 * If a shutter is enabled, the used relays can not be controlled by single relay actions!
 *
 * Bit 0: Enable shutter 1 and disable relay 1 and 2 to be controlled external.
 * Bit 1: Enable shutter 2 and disable relay 3 and 4 to be controlled external.
 * Bit 2: Enable shutter 3 and disable relay 5 and 6 to be controlled external.
 * Bit 3: Enable shutter 4 and disable relay 7 and 8 to be controlled external.
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readShutterEnable(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_SHUTTER_ENABLE);
}

/**
 * This function writes the shutter enable to persistent storage.
 * Enable or disable a shutter. There are up to 4 shutter enumerated by 1 to 4.
 * The shutter 1 corresponds to bit 0 and etc.
 * A 0 disables the shutter and a 1 enables it.
 * If a shutter is enabled, the used relays can not be controlled by single relay actions!
 *
 * Bit 0: Enable shutter 1 and disable relay 1 and 2 to be controlled external.
 * Bit 1: Enable shutter 2 and disable relay 3 and 4 to be controlled external.
 * Bit 2: Enable shutter 3 and disable relay 5 and 6 to be controlled external.
 * Bit 3: Enable shutter 4 and disable relay 7 and 8 to be controlled external.
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeShutterEnable(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_SHUTTER_ENABLE, value);

    return;
}

/**
 * This function reads the relay event config from persistent storage.
 * Enable or disable a relay event. There are up to 8 relay enumerated by 1 to 8.
 * The relay 1 corresponds to bit 0 and etc.
 * A 0 disables the event and a 1 enables it.
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readRelayEventConfig(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_RELAY_EVENT_CONFIG);
}

/**
 * This function writes the relay event config to persistent storage.
 * Enable or disable a relay event. There are up to 8 relay enumerated by 1 to 8.
 * The relay 1 corresponds to bit 0 and etc.
 * A 0 disables the event and a 1 enables it.
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeRelayEventConfig(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_RELAY_EVENT_CONFIG, value);

    return;
}

/**
 * This function reads the shutter event config from persistent storage.
 * Enable or disable a shutter event. There are up to 4 shutter enumerated by 1 to 4.
 * The shutter 1 corresponds to bit 0 and etc.
 * A 0 disables the event and a 1 enables it.
 * Note, that the shutter must be enabled.
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readShutterEventConfig(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_SHUTTER_EVENT_CONFIG);
}

/**
 * This function writes the shutter event config to persistent storage.
 * Enable or disable a shutter event. There are up to 4 shutter enumerated by 1 to 4.
 * The shutter 1 corresponds to bit 0 and etc.
 * A 0 disables the event and a 1 enables it.
 * Note, that the shutter must be enabled.
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeShutterEventConfig(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_SHUTTER_EVENT_CONFIG, value);

    return;
}

/**
 * This function reads the relay switching duty cycle from persistent storage.
 * A monostable relay is activated by using the switching current.
 * The value is given as pwm duty cycle value (3-400).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readRelaySwitchingDutyCycle(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_RELAY_SWITCHING_DUTY_CYCLE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_RELAY_SWITCHING_DUTY_CYCLE + index);
    }

    return value;
}

/**
 * This function writes the relay switching duty cycle to persistent storage.
 * A monostable relay is activated by using the switching current.
 * The value is given as pwm duty cycle value (3-400).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeRelaySwitchingDutyCycle(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_RELAY_SWITCHING_DUTY_CYCLE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_RELAY_SWITCHING_DUTY_CYCLE + index, value);
    }

    return;
}

/**
 * This function reads the relay holding duty cycle from persistent storage.
 * A monostable relay is holded in active state by using the holding current.
 * The value is given as pwm duty cycle value (3-400).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readRelayHoldingDutyCycle(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_RELAY_HOLDING_DUTY_CYCLE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_RELAY_HOLDING_DUTY_CYCLE + index);
    }

    return value;
}

/**
 * This function writes the relay holding duty cycle to persistent storage.
 * A monostable relay is holded in active state by using the holding current.
 * The value is given as pwm duty cycle value (3-400).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeRelayHoldingDutyCycle(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_RELAY_HOLDING_DUTY_CYCLE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_RELAY_HOLDING_DUTY_CYCLE + index, value);
    }

    return;
}



/**
 * This function reads the button event zone from persistent storage.
 * The zone to which the button event belongs to (255 means all zones).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readButtonEventZone(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_BUTTON_EVENT_ZONE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_BUTTON_EVENT_ZONE + index);
    }

    return value;
}

/**
 * This function writes the button event zone to persistent storage.
 * The zone to which the button event belongs to (255 means all zones).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeButtonEventZone(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_BUTTON_EVENT_ZONE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_BUTTON_EVENT_ZONE + index, value);
    }

    return;
}

/**
 * This function reads the button event sub zone from persistent storage.
 * The sub-zone to which the button event belongs to (255 means all sub-zones).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readButtonEventSubZone(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_BUTTON_EVENT_SUB_ZONE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_BUTTON_EVENT_SUB_ZONE + index);
    }

    return value;
}

/**
 * This function writes the button event sub zone to persistent storage.
 * The sub-zone to which the button event belongs to (255 means all sub-zones).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeButtonEventSubZone(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_BUTTON_EVENT_SUB_ZONE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_BUTTON_EVENT_SUB_ZONE + index, value);
    }

    return;
}

/**
 * This function reads the relay event zone from persistent storage.
 * The zone to which the relay event belongs to (255 means all zones).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readRelayEventZone(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_RELAY_EVENT_ZONE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_RELAY_EVENT_ZONE + index);
    }

    return value;
}

/**
 * This function writes the relay event zone to persistent storage.
 * The zone to which the relay event belongs to (255 means all zones).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeRelayEventZone(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_RELAY_EVENT_ZONE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_RELAY_EVENT_ZONE + index, value);
    }

    return;
}

/**
 * This function reads the relay event sub zone from persistent storage.
 * The sub-zone to which the relay event belongs to (255 means all sub-zones).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readRelayEventSubZone(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_RELAY_EVENT_SUB_ZONE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_RELAY_EVENT_SUB_ZONE + index);
    }

    return value;
}

/**
 * This function writes the relay event sub zone to persistent storage.
 * The sub-zone to which the relay event belongs to (255 means all sub-zones).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeRelayEventSubZone(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_RELAY_EVENT_SUB_ZONE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_RELAY_EVENT_SUB_ZONE + index, value);
    }

    return;
}

/**
 * This function reads the shutter event zone from persistent storage.
 * The zone to which the shutter event belongs to (255 means all zones).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readShutterEventZone(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_SHUTTER_EVENT_ZONE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_SHUTTER_EVENT_ZONE + index);
    }

    return value;
}

/**
 * This function writes the shutter event zone to persistent storage.
 * The zone to which the shutter event belongs to (255 means all zones).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeShutterEventZone(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_SHUTTER_EVENT_ZONE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_SHUTTER_EVENT_ZONE + index, value);
    }

    return;
}

/**
 * This function reads the shutter event sub zone from persistent storage.
 * The sub-zone to which the shutter event belongs to  (255 means all sub-zones).
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readShutterEventSubZone(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_SHUTTER_EVENT_SUB_ZONE > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_SHUTTER_EVENT_SUB_ZONE + index);
    }

    return value;
}

/**
 * This function writes the shutter event sub zone to persistent storage.
 * The sub-zone to which the shutter event belongs to  (255 means all sub-zones).
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeShutterEventSubZone(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_SHUTTER_EVENT_SUB_ZONE > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_SHUTTER_EVENT_SUB_ZONE + index, value);
    }

    return;
}

/**
 * This function reads the wind event zone from persistent storage.
 * The zone to which the wind event belongs to (255 means all zones).
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readWindEventZone(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_WIND_EVENT_ZONE);
}

/**
 * This function writes the wind event zone to persistent storage.
 * The zone to which the wind event belongs to (255 means all zones).
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeWindEventZone(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_WIND_EVENT_ZONE, value);

    return;
}

/**
 * This function reads the wind event sub zone from persistent storage.
 * The sub-zone to which the wind event belongs to  (255 means all sub-zones).
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readWindEventSubZone(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_WIND_EVENT_SUB_ZONE);
}

/**
 * This function writes the wind event sub zone to persistent storage.
 * The sub-zone to which the wind event belongs to  (255 means all sub-zones).
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeWindEventSubZone(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_WIND_EVENT_SUB_ZONE, value);

    return;
}

/**
 * This function reads the wind speed medium from persistent storage.
 * Medium wind speed in [0,1m/s].
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readWindSpeedMedium(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_WIND_SPEED_MEDIUM);
}

/**
 * This function writes the wind speed medium to persistent storage.
 * Medium wind speed in [0,1m/s].
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeWindSpeedMedium(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_WIND_SPEED_MEDIUM, value);

    return;
}

/**
 * This function reads the wind speed high from persistent storage.
 * High wind speed in [0,1m/s].
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readWindSpeedHigh(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_WIND_SPEED_HIGH);
}

/**
 * This function writes the wind speed high to persistent storage.
 * High wind speed in [0,1m/s].
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeWindSpeedHigh(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_WIND_SPEED_HIGH, value);

    return;
}

/**
 * This function reads the wind speed very high from persistent storage.
 * Very high wind speed in [0,1m/s].
 *
 * @return Value
 */
extern uint8_t vscp_ps_user_readWindSpeedVeryHigh(void)
{
    return vscp_ps_access_read8(VSCP_PS_USER_ADDR_WIND_SPEED_VERY_HIGH);
}

/**
 * This function writes the wind speed very high to persistent storage.
 * Very high wind speed in [0,1m/s].
 *
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeWindSpeedVeryHigh(uint8_t value)
{
    vscp_ps_access_write8(VSCP_PS_USER_ADDR_WIND_SPEED_VERY_HIGH, value);

    return;
}

/**
 * This function reads the shutter max up time from persistent storage.
 * Max. up-time (drive time from bottom to top) in 0.1s as 16-bit value.
 * Shutter 1 is at the lower address and the other shutters follow.
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readShutterMaxUpTime(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_SHUTTER_MAX_UP_TIME > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_SHUTTER_MAX_UP_TIME + index);
    }

    return value;
}

/**
 * This function writes the shutter max up time to persistent storage.
 * Max. up-time (drive time from bottom to top) in 0.1s as 16-bit value.
 * Shutter 1 is at the lower address and the other shutters follow.
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeShutterMaxUpTime(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_SHUTTER_MAX_UP_TIME > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_SHUTTER_MAX_UP_TIME + index, value);
    }

    return;
}

/**
 * This function reads the shutter max down time from persistent storage.
 * Max. down-time (drive time from top to bottom) in 0.1s as 16-bit value.
 * Shutter 1 is at the lower address and the other shutters follow.
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readShutterMaxDownTime(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_SHUTTER_MAX_DOWN_TIME > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_SHUTTER_MAX_DOWN_TIME + index);
    }

    return value;
}

/**
 * This function writes the shutter max down time to persistent storage.
 * Max. down-time (drive time from top to bottom) in 0.1s as 16-bit value.
 * Shutter 1 is at the lower address and the other shutters follow.
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeShutterMaxDownTime(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_SHUTTER_MAX_DOWN_TIME > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_SHUTTER_MAX_DOWN_TIME + index, value);
    }

    return;
}

/**
 * This function reads the shutter turn time from persistent storage.
 * Max. turn-time (turn 90°) in 0.1s as 16-bit value.
 * Shutter 1 is at the lower address and the other shutters follow.
 *
 * @param[in] index Index
 * @return Value
 */
extern uint8_t vscp_ps_user_readShutterTurnTime(uint8_t index)
{
    uint8_t value = 0;

    if (VSCP_PS_USER_SIZE_SHUTTER_TURN_TIME > index)
    {
         value = vscp_ps_access_read8(VSCP_PS_USER_ADDR_SHUTTER_TURN_TIME + index);
    }

    return value;
}

/**
 * This function writes the shutter turn time to persistent storage.
 * Max. turn-time (turn 90°) in 0.1s as 16-bit value.
 * Shutter 1 is at the lower address and the other shutters follow.
 *
 * @param[in] index Index
 * @param[in] value Value to write
 */
extern void vscp_ps_user_writeShutterTurnTime(uint8_t index, uint8_t value)
{
    if (VSCP_PS_USER_SIZE_SHUTTER_TURN_TIME > index)
    {
        vscp_ps_access_write8(VSCP_PS_USER_ADDR_SHUTTER_TURN_TIME + index, value);
    }

    return;
}

/*******************************************************************************
    LOCAL FUNCTIONS
*******************************************************************************/
