/* The MIT License (MIT)
 *
 * Copyright (c) 2014 - 2019, Andreas Merkle
 * http://www.blue-andi.de
 * vscp@blue-andi.de
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/*******************************************************************************
    DESCRIPTION
*******************************************************************************/
/**
@brief  Weather
@file   vscp_evt_weather.c
@author Andreas Merkle, http://www.blue-andi.de

@section desc Description
@see vscp_evt_weather.h

This file is automatically generated. Don't change it manually.

*******************************************************************************/

/*******************************************************************************
    INCLUDES
*******************************************************************************/
#include "vscp_evt_weather.h"
#include "vscp_core.h"
#include "vscp_class_l1.h"
#include "vscp_type_weather.h"

/*******************************************************************************
    COMPILER SWITCHES
*******************************************************************************/

/*******************************************************************************
    CONSTANTS
*******************************************************************************/

/*******************************************************************************
    MACROS
*******************************************************************************/

/*******************************************************************************
    TYPES AND STRUCTURES
*******************************************************************************/

/*******************************************************************************
    VARIABLES
*******************************************************************************/

/*******************************************************************************
    FUNCTIONS
*******************************************************************************/

/**
 * General event
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_weather_sendGeneralEvent(void)
{
	vscp_TxMessage	txMsg;

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_WEATHER, VSCP_TYPE_WEATHER_GENERAL, VSCP_PRIORITY_3_NORMAL);

	txMsg.dataNum = 0;

	return vscp_core_sendEvent(&txMsg);
}

/* "Season winter" not supported. No frame defined. */

/* "Season spring" not supported. No frame defined. */

/* "Season summer" not supported. No frame defined. */

/* "Autumn summer" not supported. No frame defined. */

/* "No wind" not supported. No frame defined. */

/* "Low wind" not supported. No frame defined. */

/* "Medium wind" not supported. No frame defined. */

/* "High wind" not supported. No frame defined. */

/* "Very high wind" not supported. No frame defined. */

/* "Air foggy" not supported. No frame defined. */

/* "Air freezing" not supported. No frame defined. */

/* "Air Very cold" not supported. No frame defined. */

/* "Air cold" not supported. No frame defined. */

/* "Air normal" not supported. No frame defined. */

/* "Air hot" not supported. No frame defined. */

/* "Air very hot" not supported. No frame defined. */

/* "Pollution low" not supported. No frame defined. */

/* "Pollution medium" not supported. No frame defined. */

/* "Pollution high" not supported. No frame defined. */

/* "Air humid" not supported. No frame defined. */

/* "Air dry" not supported. No frame defined. */

/* "Soil humid" not supported. No frame defined. */

/* "Soil dry" not supported. No frame defined. */

/* "Rain none" not supported. No frame defined. */

/* "Rain light" not supported. No frame defined. */

/* "Rain heavy" not supported. No frame defined. */

/* "Rain very heavy" not supported. No frame defined. */

/* "Sun none" not supported. No frame defined. */

/* "Sun light" not supported. No frame defined. */

/* "Sun heavy" not supported. No frame defined. */

/* "Snow none" not supported. No frame defined. */

/* "Snow light" not supported. No frame defined. */

/* "Snow heavy" not supported. No frame defined. */

/* "Dew point" not supported. No frame defined. */

/* "Storm" not supported. No frame defined. */

/* "Flood" not supported. No frame defined. */

/* "Earthquake" not supported. No frame defined. */

/* "Nuclear disaster" not supported. No frame defined. */

/* "Fire" not supported. No frame defined. */

/* "Lightning" not supported. No frame defined. */

/* "UV Radiation low" not supported. No frame defined. */

/* "UV Radiation medium" not supported. No frame defined. */

/* "UV Radiation normal" not supported. No frame defined. */

/* "UV Radiation high" not supported. No frame defined. */

/* "UV Radiation very high" not supported. No frame defined. */

/* "Warning level 1" not supported. No frame defined. */

/* "Warning level 2" not supported. No frame defined. */

/* "Warning level 3" not supported. No frame defined. */

/* "Warning level 4" not supported. No frame defined. */

/* "Warning level 5" not supported. No frame defined. */

/* "Armageddon" not supported. No frame defined. */

/* "UV Index" not supported. No frame defined. */

