/* The MIT License (MIT)
 *
 * Copyright (c) 2014 - 2019, Andreas Merkle
 * http://www.blue-andi.de
 * vscp@blue-andi.de
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/*******************************************************************************
    DESCRIPTION
*******************************************************************************/
/**
@brief  Diagnostic
@file   vscp_evt_diagnostic.c
@author Andreas Merkle, http://www.blue-andi.de

@section desc Description
@see vscp_evt_diagnostic.h

This file is automatically generated. Don't change it manually.

*******************************************************************************/

/*******************************************************************************
    INCLUDES
*******************************************************************************/
#include "vscp_evt_diagnostic.h"
#include "vscp_core.h"
#include "vscp_class_l1.h"
#include "vscp_type_diagnostic.h"

/*******************************************************************************
    COMPILER SWITCHES
*******************************************************************************/

/*******************************************************************************
    CONSTANTS
*******************************************************************************/

/*******************************************************************************
    MACROS
*******************************************************************************/

/*******************************************************************************
    TYPES AND STRUCTURES
*******************************************************************************/

/*******************************************************************************
    VARIABLES
*******************************************************************************/

/*******************************************************************************
    FUNCTIONS
*******************************************************************************/

/**
 * General event
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_diagnostic_sendGeneralEvent(void)
{
	vscp_TxMessage	txMsg;

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_DIAGNOSTIC, VSCP_TYPE_DIAGNOSTIC_GENERAL, VSCP_PRIORITY_3_NORMAL);

	txMsg.dataNum = 0;

	return vscp_core_sendEvent(&txMsg);
}

/* "Overvoltage" not supported. No frame defined. */

/* "Undervoltage" not supported. No frame defined. */

/* "USB VBUS low" not supported. No frame defined. */

/* "Battery voltage low" not supported. No frame defined. */

/* "Battery full voltage" not supported. No frame defined. */

/* "Battery error" not supported. No frame defined. */

/* "Battery OK" not supported. No frame defined. */

/* "Over current" not supported. No frame defined. */

/* "Circuit error" not supported. No frame defined. */

/* "Short circuit" not supported. No frame defined. */

/* "Open Circuit" not supported. No frame defined. */

/* "Moist" not supported. No frame defined. */

/* "Wire failure" not supported. No frame defined. */

/* "Wireless faliure" not supported. No frame defined. */

/* "IR failure" not supported. No frame defined. */

/* "1-wire failure" not supported. No frame defined. */

/* "RS-222 failure" not supported. No frame defined. */

/* "RS-232 failure" not supported. No frame defined. */

/* "RS-423 failure" not supported. No frame defined. */

/* "RS-485 failure" not supported. No frame defined. */

/* "CAN failure" not supported. No frame defined. */

/* "LAN failure" not supported. No frame defined. */

/* "USB failure" not supported. No frame defined. */

/* "Wifi failure" not supported. No frame defined. */

/* "NFC/RFID failure" not supported. No frame defined. */

/* "Low signal" not supported. No frame defined. */

/* "High signal" not supported. No frame defined. */

/* "ADC failure" not supported. No frame defined. */

/* "ALU failure" not supported. No frame defined. */

/* "Assert" not supported. No frame defined. */

/* "DAC failure" not supported. No frame defined. */

/* "DMA failure" not supported. No frame defined. */

/* "Ethernet failure" not supported. No frame defined. */

/* "Exception" not supported. No frame defined. */

/* "FPU failure" not supported. No frame defined. */

/* "GPIO failure" not supported. No frame defined. */

/* "I2C failure" not supported. No frame defined. */

/* "I2S failure" not supported. No frame defined. */

/* "Invalid configuration" not supported. No frame defined. */

/* "MMU failure" not supported. No frame defined. */

/* "NMI failure" not supported. No frame defined. */

/* "Overheat" not supported. No frame defined. */

/* "PLL fail" not supported. No frame defined. */

/* "POR failure" not supported. No frame defined. */

/* "PWM failure" not supported. No frame defined. */

/* "RAM failure" not supported. No frame defined. */

/* "ROM failure" not supported. No frame defined. */

/* "SPI failure" not supported. No frame defined. */

/* "Stack failure" not supported. No frame defined. */

/* "LIN bus failure" not supported. No frame defined. */

/* "UART failure" not supported. No frame defined. */

/* "Unhandled interrupt" not supported. No frame defined. */

/* "Memory failure" not supported. No frame defined. */

/* "Variable range failure" not supported. No frame defined. */

/* "WDT failure" not supported. No frame defined. */

/* "EEPROM failure" not supported. No frame defined. */

/* "Encryption failure" not supported. No frame defined. */

/* "Bad user input failure" not supported. No frame defined. */

/* "Decryption failure" not supported. No frame defined. */

/* "Noise" not supported. No frame defined. */

/* "Boot loader failure" not supported. No frame defined. */

/* "Program flow failure" not supported. No frame defined. */

/* "RTC faiure" not supported. No frame defined. */

/* "System test failure" not supported. No frame defined. */

/* "Sensor failure" not supported. No frame defined. */

/* "Safe state entered" not supported. No frame defined. */

/* "Signal implausible" not supported. No frame defined. */

/* "Storage fail" not supported. No frame defined. */

/* "Self test OK" not supported. No frame defined. */

/* "ESD/EMC/EMI failure" not supported. No frame defined. */

/* "Timeout" not supported. No frame defined. */

/* "LCD failure" not supported. No frame defined. */

/* "Touch panel failure" not supported. No frame defined. */

/* "No load" not supported. No frame defined. */

/* "Cooling failure" not supported. No frame defined. */

/* "Heating failure" not supported. No frame defined. */

/* "Transmission failure" not supported. No frame defined. */

/* "Receiption failure" not supported. No frame defined. */

/* "External IC failure" not supported. No frame defined. */

