/* The MIT License (MIT)
 *
 * Copyright (c) 2014 - 2019, Andreas Merkle
 * http://www.blue-andi.de
 * vscp@blue-andi.de
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/*******************************************************************************
    DESCRIPTION
*******************************************************************************/
/**
@brief  Double precision floating point measurement
@file   vscp_evt_measurement64.c
@author Andreas Merkle, http://www.blue-andi.de

@section desc Description
@see vscp_evt_measurement64.h

This file is automatically generated. Don't change it manually.

*******************************************************************************/

/*******************************************************************************
    INCLUDES
*******************************************************************************/
#include "vscp_evt_measurement64.h"
#include "vscp_core.h"
#include "vscp_class_l1.h"
#include "vscp_type_measurement64.h"

/*******************************************************************************
    COMPILER SWITCHES
*******************************************************************************/

/*******************************************************************************
    CONSTANTS
*******************************************************************************/

/*******************************************************************************
    MACROS
*******************************************************************************/

/*******************************************************************************
    TYPES AND STRUCTURES
*******************************************************************************/

/*******************************************************************************
    VARIABLES
*******************************************************************************/

/*******************************************************************************
    FUNCTIONS
*******************************************************************************/

/**
 * General event
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendGeneralEvent(void)
{
	vscp_TxMessage	txMsg;

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_GENERAL, VSCP_PRIORITY_3_NORMAL);

	txMsg.dataNum = 0;

	return vscp_core_sendEvent(&txMsg);
}

/* "Count" not supported. No frame defined. */

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendLengthDistance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_LENGTH, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendMass(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_MASS, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendTime(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_TIME, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendElectricCurrent(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ELECTRIC_CURRENT, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendTemperature(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_TEMPERATURE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendAmountOfSubstance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_AMOUNT_OF_SUBSTANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendLuminousIntensityIntensityOfLight(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_INTENSITY_OF_LIGHT, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendFrequency(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_FREQUENCY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendRadioactivityAndOtherRandomEvents(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_RADIOACTIVITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendForce(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_FORCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendPressure(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_PRESSURE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendEnergy(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ENERGY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendPower(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_POWER, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendElectricalCharge(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ELECTRICAL_CHARGE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendElectricalPotentialVoltage(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ELECTRICAL_POTENTIAL, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendElectricalCapacitance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ELECTRICAL_CAPACITANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendElectricalResistance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ELECTRICAL_RESISTANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendElectricalConductance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ELECTRICAL_CONDUCTANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendMagneticFieldStrength(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_MAGNETIC_FIELD_STRENGTH, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendMagneticFlux(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_MAGNETIC_FLUX, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendMagneticFluxDensity(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_MAGNETIC_FLUX_DENSITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendInductance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_INDUCTANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendLuminousFlux(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_FLUX_OF_LIGHT, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendIlluminance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ILLUMINANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendRadiationDose(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_RADIATION_DOSE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendCatalyticActivity(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_CATALYTIC_ACITIVITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendVolume(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_VOLUME, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSoundIntensity(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SOUND_INTENSITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendAngle(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ANGLE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendPositionWgs84(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_POSITION, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSpeed(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SPEED, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendAcceleration(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ACCELERATION, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendTension(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_TENSION, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendDampMoistHygrometerReading(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_HUMIDITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendFlow(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_FLOW, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendThermalResistance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_THERMAL_RESISTANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendRefractiveOpticalPower(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_REFRACTIVE_POWER, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendDynamicViscosity(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_DYNAMIC_VISCOSITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSoundImpedance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SOUND_IMPEDANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSoundResistance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SOUND_RESISTANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendElectricElastance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ELECTRIC_ELASTANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendLuminousEnergy(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_LUMINOUS_ENERGY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendLuminance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_LUMINANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendChemicalConcentration(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_CHEMICAL_CONCENTRATION, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendReserved(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_RESERVED46, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendDoseEquivalent(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_DOSE_EQVIVALENT, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendReserved(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_RESERVED48, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendDewPoint(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_DEWPOINT, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendRelativeLevel(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_RELATIVE_LEVEL, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendAltitude(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_ALTITUDE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendArea(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_AREA, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendRadiantIntensity(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_RADIANT_INTENSITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendRadiance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_RADIANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendIrradianceExitanceRadiosity(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_IRRADIANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSpectralRadiance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SPECTRAL_RADIANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSpectralIrradiance(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SPECTRAL_IRRADIANCE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSoundPressureAcousticPressure(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SOUND_PRESSURE, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSoundEnergyDensity(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SOUND_DENSITY, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

/**
 * Count
 * 
 * @param[in] dataCoding Data coding.
 * @param[in] data Data with format defined by byte 0.  (array[7])
 * @param[in] datasize Size in byte.
 * 
 * @return If event is sent, it will return TRUE otherwise FALSE.
 */
extern BOOL vscp_evt_protocol_sendSoundLevel(uint8_t dataCoding, uint8_t const * const data, uint8_t dataSize)
{
	vscp_TxMessage	txMsg;
	uint8_t       	size	= 0;
	uint8_t       	index	= 0;

	if (NULL == data) || (0 == dataSize)
	{
		return FALSE;
	}

	vscp_core_prepareTxMessage(&txMsg, VSCP_CLASS_L1_MEASUREMENT64, VSCP_TYPE_MEASUREMENT64_SOUND_LEVEL, VSCP_PRIORITY_3_NORMAL);

	txMsg.data[0] = dataCoding;
	size += 1;

	for(index = 0; index < dataSize; ++index)
	{
		txMsg.data[1 + index] = data[index];
		size += 1;

		if (VSCP_L1_DATA_SIZE <= size)
		{
			break;
		}
	}

	txMsg.dataNum = size;

	return vscp_core_sendEvent(&txMsg);
}

