/* The MIT License (MIT)
 *
 * Copyright (c) 2014 - 2019, Andreas Merkle
 * http://www.blue-andi.de
 * vscp@blue-andi.de
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */

/*******************************************************************************
    DESCRIPTION
*******************************************************************************/
/**
@brief  Error
@file   vscp_evt_error.c
@author Andreas Merkle, http://www.blue-andi.de

@section desc Description
@see vscp_evt_error.h

This file is automatically generated. Don't change it manually.

*******************************************************************************/

/*******************************************************************************
    INCLUDES
*******************************************************************************/
#include "vscp_evt_error.h"
#include "vscp_core.h"
#include "vscp_class_l1.h"
#include "vscp_type_error.h"

/*******************************************************************************
    COMPILER SWITCHES
*******************************************************************************/

/*******************************************************************************
    CONSTANTS
*******************************************************************************/

/*******************************************************************************
    MACROS
*******************************************************************************/

/*******************************************************************************
    TYPES AND STRUCTURES
*******************************************************************************/

/*******************************************************************************
    VARIABLES
*******************************************************************************/

/*******************************************************************************
    FUNCTIONS
*******************************************************************************/

/* "Success" not supported. No frame defined. */

/* "Error" not supported. No frame defined. */

/* "Channel error" not supported. No frame defined. */

/* "Fifo empty error" not supported. No frame defined. */

/* "Fifo full error" not supported. No frame defined. */

/* "Fifo size error" not supported. No frame defined. */

/* "Fifo wait error" not supported. No frame defined. */

/* "Generic error" not supported. No frame defined. */

/* "Hardware error" not supported. No frame defined. */

/* "initialization error" not supported. No frame defined. */

/* "Missing initialization error" not supported. No frame defined. */

/* "Initialization ready" not supported. No frame defined. */

/* "Not supported" not supported. No frame defined. */

/* "Overrun error" not supported. No frame defined. */

/* "Receiver empty error" not supported. No frame defined. */

/* "Register error" not supported. No frame defined. */

/* "Transmitter full error" not supported. No frame defined. */

/* "Library error" not supported. No frame defined. */

/* "Procedural address error" not supported. No frame defined. */

/* "Only one instance error" not supported. No frame defined. */

/* "Sub driver error" not supported. No frame defined. */

/* "Timeout error" not supported. No frame defined. */

/* "Not open error" not supported. No frame defined. */

/* "Parameter error" not supported. No frame defined. */

/* "Memory error" not supported. No frame defined. */

/* "Internal error" not supported. No frame defined. */

/* "Communication error" not supported. No frame defined. */

/* "User error" not supported. No frame defined. */

/* "Password error" not supported. No frame defined. */

/* "Connection error" not supported. No frame defined. */

/* "Invalid handle error" not supported. No frame defined. */

/* "Operation failed error" not supported. No frame defined. */

/* "Supplied buffer is to small to fit content" not supported. No frame defined. */

/* "Requested item is unknown" not supported. No frame defined. */

/* "Name is already in use" not supported. No frame defined. */

/* "Error when writing data" not supported. No frame defined. */

/* "Operation stopped or aborted" not supported. No frame defined. */

/* "Pointer with invalid value" not supported. No frame defined. */

